version: '3'

services:
  api:
    build: .
    container_name: bims
    image: bims:0.1
    command: gunicorn bims_landing_page.wsgi:application --bind 0.0.0.0:8001
    restart: unless-stopped
    env_file:
      - .env.backend
    networks:
      - bims-network
    volumes:
      - bims-media:/home/app/web/media
      - bims-static:/home/app/web/static-live
    depends_on: 
      - db

  db:
    image: postgres
    container_name: bimsdb
    env_file:
      - .env.db
    volumes:
      - bims-db:/var/lib/postgresql/data
    networks:
      - bims-network

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - bims-static:/home/app/web/static-live
      - bims-media:/home/app/web/media
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - bims-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  bims-network:
    driver: bridge

volumes:
  bims-db:
  bims-media:
  bims-static:
