# Generated by Django 3.1.4 on 2021-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='no_of_users_of_app',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
