# Generated by Django 3.1.4 on 2021-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20210704_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='otp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
