# Generated by Django 3.1.4 on 2021-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_contact_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Enter Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(default='Enter Your Contact No.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='industry_name',
            field=models.CharField(default="Industry's Name", max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='otp',
            field=models.CharField(default='OTP', max_length=10),
        ),
    ]
