# Generated by Django 3.1.4 on 2021-08-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_auto_20210801_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAndOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
